# Solution for Predicting Olympic Medal Count
We have a historical dataset on the modern Olympic Games, including all the Games from Athens 1896 to Rio 2012. We want to predict the number of medals for the 2016 Olympic Games. The dataset can be divided in three tables, the ground truth, country of olympics and the specific event with medals.\
Here are the attributes of our tables.

<p><c>
    <img src="dataset.png" alt="Olympic Logo" width=500/>
</c></p>

Here we provide a solution for predicting Olympic Medal Count in 2016. Now you need to **follow the provided solution and select a subset of features** you think is helpful for predicting the Medal Count of the coming Olympic Games  in Tokyo. You are required to finish the tasks below:
### Steps:

#### 1. learn about the dataset and the task of predicting Olympic Medal Count in the first cell called load data (input, ground truth, data, regressive model);
#### 2. load the suggested features from experts and Automatic algorithms and <span style="color:blue">check the features in the 3rd cell by clicking the button on the right of the cell</span>.
#### 3. Checked the information of the features in the table view and select a subset of features by ticking the checkbox, submit your selection by clicking the <span style="color:blue">blue button Submit Selection in the view</span>.
#### 4. Copy the feature ids and evaluate these features in the evaluation cell by pasting the id list in the <span style="color:blue">auto_human_feature_matrix.iloc[:,[feature id list]</span>.

#### You can select and evaluate the features iteratively or create new features from the three tables by yourself.

## Load data

In [1]:
# load data and groung truth
import os
import pandas as pd
import utils_original as utils
import foldCode1 as load_df
import foldCode2 as our_model

DATA_DIR = os.path.join(os.getcwd(),"data/olympic_games_data")
es = utils.load_entityset(data_dir=DATA_DIR)
groundtruth_table, countries_table, events_table, cutoff_times_gt, dates, labels = load_df.loadData(es, DATA_DIR)

/home/study816/suggest-features/naturalStudy_815/utils_original.py:152: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  countries['Country'] = countries['Country'].str.replace('*', '')

You can add new cells to print the 3 tables (groundtruth_table, countries_table, events_table) and the input (dates) and labels.

## <span style="color:brown">Generate Features</span> (Edit)

In [2]:
select_human_feature_names, select_human_features = load_df.human_features() #7
all_features = pd.read_csv("features/natural_features_all_815.csv")

# Check feature matrix
all_features

,MEAN(countries_at_olympic_games.NUM_UNIQUE(medals_won.Event)),ABSOLUTE(MEAN(medals_won.Height)),MIN(countries_at_olympic_games.MEAN(medals_won.Height)),MEAN(medals_won.Height),MEAN(countries_at_olympic_games.COUNT(medals_won)),MEAN(countries_at_olympic_games.SUM(medals_won.Height)),MAX(countries_at_olympic_games.MIN(medals_won.Age)),MEAN(countries_at_olympic_games.SUM(medals_won.Weight)),"PERCENTILE(TREND(medals_won.Height, Year))",MIN(countries_at_olympic_games.SKEW(medals_won.Age)),...,COUNT(medaling_athletes WHERE athlete.Gender = Men),"TREND(countries_at_olympic_games.MAX(medals_won.Age), Year)",ABSOLUTE(SKEW(medals_won.Age)),PERCENTILE(COUNT(medals_won)),SUM(countries_at_olympic_games.MIN(medals_won.Age)),SKEW(countries_at_olympic_games.MAX(medals_won.Age)),SKEW(countries_at_olympic_games.MEAN(medals_won.Weight)),"RATIO(COUNT(athletes WHERE Gender = Men), COUNT(athletes WHERE Gender = Women))","RATIO(COUNT(athletes WHERE Gender = Women), COUNT(athletes.Athelete))",PERCENTILE(MEAN(medals_won.Height))
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6,NaN,NaN,0.502273,0.0,NaN,NaN,10.0,0.0,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,52,NaN,NaN,0.502273,0.0,NaN,NaN,10.0,0.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33,NaN,NaN,0.502273,0.0,NaN,NaN,10.0,0.0,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6,NaN,NaN,0.502273,0.0,NaN,NaN,10.0,0.0,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7,NaN,NaN,0.502273,0.0,NaN,NaN,10.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146,1.857143,173.846154,166.0,173.846154,1.857143,322.857143,31.0,107.142857,0.318681,-1.732051,...,1,-0.000156,0.073284,0.702273,177.0,-0.710342,-0.050544,10.0,0.0,0.341085
1147,2.285714,173.250000,158.0,173.250000,2.285714,396.000000,24.0,155.428571,0.538462,-0.585583,...,18,-0.000120,0.221115,0.720455,146.0,-0.178474,0.059369,10.0,0.0,0.294574
1148,1.444444,171.916667,157.0,171.916667,1.444444,229.222222,30.0,90.555556,0.395604,NaN,...,0,0.000147,1.194443,0.702273,233.0,0.838972,0.687104,0.0,1.0,0.240310
1149,1.000000,183.000000,183.0,183.000000,1.000000,183.000000,23.0,90.000000,NaN,NaN,...,1,NaN,NaN,0.429545,23.0,NaN,NaN,10.0,0.0,0.899225
1150,1.000000,175.000000,175.0,175.000000,1.000000,175.000000,40.0,67.000000,NaN,NaN,...,1,NaN,NaN,0.429545,40.0,NaN,NaN,10.0,0.0,0.410853

In [21]:
#check features

In [52]:
# OPTIONAL: write new features
# all_features.insert()

# OPTIONAL: you can check single feature:
# all_features.iloc[:, #id]

# MUST EDIT: feature selection: input feature ID in the list below:
feature_id = list(range(49,99)) # index 0-98

## Evaluate features with given models

In [53]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import ExtraTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import LinearSVC
from sklearn.svm import LinearSVR
from sklearn.linear_model import ARDRegression
import utils_original as utils

# parameters of the regressive model
pipeline_preprocessing = [("imputer",
                            SimpleImputer()),
                            ("scaler", RobustScaler(with_centering=True))]
splitter = utils.TimeSeriesSplitByDate(dates=dates, earliest_date=pd.Timestamp('01/01/2012')) 

# If you want to input all features
# all_X = all_features.values  

# Take your selection as input
all_X = all_features.iloc[:, feature_id].values

### Run Models <span style="color:brown">(No changes to code are required)</span>
If you don't want to use a model, you can comment specific lines of code.

In [54]:
# Random Forest Regression
rf_regressor = RandomForestRegressor(n_estimators=300, random_state=50)  
pipeline_reg0 = Pipeline(pipeline_preprocessing + [('rf_reg', rf_regressor)])
regression_score = utils.fit_and_score(all_X, labels, splitter, pipeline_reg0)
print("RandomForest Reg:", regression_score)
# --------------------------------------------------------------------------------------------------------------------

# Linear Regression
# linear_reg = LinearRegression()
# pipeline_reg1 = Pipeline(pipeline_preprocessing + [('linear_reg', linear_reg)])
# regression_score1 = utils.fit_and_score(all_X, labels, splitter, pipeline_reg1)
# print("Linear Reg: ", regression_score1)
# --------------------------------------------------------------------------------------------------------------------

# Logistic Regression
# logistic_reg = LogisticRegression()
# pipeline_reg2 = Pipeline(pipeline_preprocessing + [('logistic_reg', logistic_reg)])
# regression_score2 = utils.fit_and_score(all_X, labels, splitter, pipeline_reg2)
# print("Logistic Reg: ", regression_score2)
# --------------------------------------------------------------------------------------------------------------------

# SGD Regression
# sgd_reg = SGDRegressor()
# pipeline_reg3 = Pipeline(pipeline_preprocessing + [('sgd_reg', sgd_reg)])
# regression_score3 = utils.fit_and_score(all_X, labels, splitter, pipeline_reg3)
# print("SGD Reg: ", regression_score3) 
# --------------------------------------------------------------------------------------------------------------------

# KNN Regression
# knn_reg = KNeighborsRegressor()
# pipeline_reg4 = Pipeline(pipeline_preprocessing + [('knn_reg', knn_reg)])
# regression_score4 = utils.fit_and_score(all_X, labels, splitter, pipeline_reg4)
# print("KNN Reg: ", regression_score4)
# --------------------------------------------------------------------------------------------------------------------

# MLP Regression
# mlp_reg = MLPRegressor()
# pipeline_reg5 = Pipeline(pipeline_preprocessing + [('mlp_reg', mlp_reg)])
# regression_score5 = utils.fit_and_score(all_X, labels, splitter, pipeline_reg5)
# print("MLP Reg: ", regression_score5)
# --------------------------------------------------------------------------------------------------------------------

# DecisionTree Regression
decisionTree_reg = DecisionTreeRegressor()
pipeline_reg6 = Pipeline(pipeline_preprocessing + [('decisionTree_reg', decisionTree_reg)])
regression_score6 = utils.fit_and_score(all_X, labels, splitter, pipeline_reg6)
print("decisionTree Reg: ", regression_score6)
# --------------------------------------------------------------------------------------------------------------------

# ExtTree Regression
# extTree_reg = ExtraTreeRegressor()
# pipeline_reg7 = Pipeline(pipeline_preprocessing + [('extTree_reg', extTree_reg)])
# regression_score7 = utils.fit_and_score(all_X, labels, splitter, pipeline_reg7)
# print("ExtTree Reg: ", regression_score7)
# --------------------------------------------------------------------------------------------------------------------

# GradientBoosting Regression
gb_reg = GradientBoostingRegressor()
pipeline_reg8 = Pipeline(pipeline_preprocessing + [('gb_reg', gb_reg)])
regression_score8 = utils.fit_and_score(all_X, labels, splitter, pipeline_reg8)
print("GradientBoosting Reg: ", regression_score8)
# --------------------------------------------------------------------------------------------------------------------

# LinearSVC Regression
# svc_reg = LinearSVC()
# pipeline_reg9 = Pipeline(pipeline_preprocessing + [('svc_reg', svc_reg)])
# regression_score9 = utils.fit_and_score(all_X, labels, splitter, pipeline_reg9)
# print("svc Reg: ", regression_score9)
# --------------------------------------------------------------------------------------------------------------------

# LinearSVR Regression
svr_reg = LinearSVR()
pipeline_reg10 = Pipeline(pipeline_preprocessing + [('svr_reg', svr_reg)])
regression_score10 = utils.fit_and_score(all_X, labels, splitter, pipeline_reg10)
print("svr Reg: ", regression_score10)
# --------------------------------------------------------------------------------------------------------------------

# ARD Regression
# ard_reg = ARDRegression()
# pipeline_reg11 = Pipeline(pipeline_preprocessing + [('ard_reg', ard_reg)])
# regression_score11 = utils.fit_and_score(all_X, labels, splitter, pipeline_reg11)
# print("ard Reg: ", regression_score11)
# --------------------------------------------------------------------------------------------------------------------

RandomForest Reg:          r2       mse Olympics Year
0  0.816879  60.73779    2016-08-05
decisionTree Reg:           r2        mse Olympics Year
0  0.770724  76.046512    2016-08-05
GradientBoosting Reg:           r2        mse Olympics Year
0  0.805368  64.555775    2016-08-05
svr Reg:           r2        mse Olympics Year
0  0.844255  51.657717    2016-08-05

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "

### Check the importance score of selected features (Select a model and get the score of features)

In [50]:
feature_imp = utils.get_feature_importances(pipeline_reg0,                     # select the regressive model for computing important scores of features (Default: RandomForest)
#                                               all_features,                  # Compute the score of all features
                                            all_features.iloc[:, feature_id], # Compute the score of selected features: 
                                            labels, splitter, 100)
 
test_date = pd.Timestamp('08/05/2016')
feature_imp[test_date] #.reset_index(drop=True)

    Importance                                            Feature
21    0.828446  SUM(medaling_athletes.NUM_UNIQUE(athletes.Athe...
40    0.065708  COUNT(medaling_athletes WHERE athlete.Gender =...
37    0.009447  MIN(countries_at_olympic_games.SUM(medals_won....
11    0.007807         PERCENTILE(TREND(medals_won.Weight, Year))
25    0.007797  MAX(countries_at_olympic_games.SUM(medals_won....
8     0.006222  MIN(countries_at_olympic_games.SUM(medals_won....
1     0.004881                 PERCENTILE(MIN(medals_won.Weight))
3     0.003077  TREND(countries_at_olympic_games.MAX(medals_wo...
13    0.003018                    PERCENTILE(gdpPppPerCapitaRank)
10    0.002991  MEAN(countries_at_olympic_games.NUM_UNIQUE(med...
29    0.002940  SKEW(countries_at_olympic_games.NUM_UNIQUE(med...
28    0.002924  NUM_UNIQUE(countries_at_olympic_games.MODE(med...
15    0.002855  MEAN(countries_at_olympic_games.MAX(medals_won...
9     0.002784  MEAN(countries_at_olympic_games.MEAN(medals_wo...
35    0.002737  MAX(countries_at_olympic_games.SUM(medals_won....
22    0.002494                  ABSOLUTE(MEAN(medals_won.Weight))
19    0.002342  SUM(countries_at_olympic_games.MIN(medals_won....
0     0.002287                PERCENTILE(MEAN(medals_won.Weight))
6     0.002271  SKEW(countries_at_olympic_games.NUM_UNIQUE(med...
12    0.002240  MAX(countries_at_olympic_games.SKEW(medals_won...
31    0.002181           PERCENTILE(NUM_UNIQUE(medals_won.Event))
36    0.002179                    ABSOLUTE(populationDensitySqMi)
39    0.002154                              populationDensitySqMi
34    0.002108      PERCENTILE(COUNT(countries_at_olympic_games))
14    0.001969                   PERCENTILE(SKEW(medals_won.Age))
17    0.001969  NUM_UNIQUE(countries_at_olympic_games.olympic_...
26    0.001799                      ABSOLUTE(MAX(medals_won.Age))
30    0.001774                 PERCENTILE(MAX(medals_won.Weight))
38    0.001767                       NUM_UNIQUE(medals_won.Event)
32    0.001660  TREND(countries_at_olympic_games.MIN(medals_wo...
4     0.001623                             MAX(medals_won.Weight)
5     0.001573  COUNT(medaling_athletes WHERE athlete.Gender =...
2     0.001533                  ABSOLUTE(SKEW(medals_won.Height))
33    0.001519  SKEW(countries_at_olympic_games.MAX(medals_won...
27    0.001519  TREND(countries_at_olympic_games.SKEW(medals_w...
18    0.001502           ABSOLUTE(TREND(medals_won.Weight, Year))
16    0.001444              ABSOLUTE(TREND(medals_won.Age, Year))
24    0.001361                PERCENTILE(SKEW(medals_won.Height))
23    0.001340  TREND(countries_at_olympic_games.MAX(medals_wo...
7     0.000992  SKEW(countries_at_olympic_games.MIN(medals_won...
20    0.000765  MODE(medals_won.countries_at_olympic_games.Oly...

In [ ]:
# all features:  63.49172  
# ----  SUM(medaling_athletes.NUM_UNIQUE(athletes.Athe      70  
# ----  COUNT(medaling_athletes WHERE athlete.Gender =      54

# feature_id = [6,9,10,14,15,16,22,27,28,30,36,38,44,54,58,62,69,75,81,83,90,92]:  
# ----  MIN(countries_at_olympic_games.COUNT(medals_won))   16
# ----  COUNT(medaling_athletes WHERE athlete.Gender        54

# feature_id = [:49]  75.563839
# feature_id = [49:]  60.73
# feature_id = [18,20,37,44,54,70,89,96,97]

70  89  54  
# feature_id = [0,54,70,89]